import express from "express";
import cors from "cors";
import { env } from "./config/env";
import { startBackgroundJobs } from "./jobs";
import healthRouter from "./routes/health.routes";
import authRouter from "./routes/auth.routes";
import componentRouter from "./routes/component.routes";
import departmentRouter from "./routes/department.routes";
import courseRouter from "./routes/course.routes";
import sectionRouter from "./routes/section.routes";
import labRouter from "./routes/lab.routes";
import routineSlotRouter from "./routes/routine-slot.routes";
import experimentRouter from "./routes/experiment.routes";
import sessionRouter from "./routes/session.routes";
import analyticsRouter from "./routes/analytics.routes";
import stockRouter from "./routes/stock.routes";
import quotaRouter from "./routes/quota.routes";
import userRouter from "./routes/user.routes";
import availabilityRouter from "./routes/availability.routes";
import requisitionRouter from "./routes/requisition.routes";
import borrowRouter from "./routes/borrow.routes";
import purchaseRouter from "./routes/purchase.routes";
import notificationRouter from "./routes/notification.routes";
import damageRouter from "./routes/damage.routes";
import suggestionRouter from "./routes/suggestion.routes";
import penaltyRouter from "./routes/penalty.routes";
import auditRouter from "./routes/audit.routes";
import { auditSuccessfulWrites } from "./middleware/audit";

const app = express();

app.use(cors());
app.use(express.json());
app.use(healthRouter);
app.use("/api", auditSuccessfulWrites);
app.use("/api", authRouter);
app.use("/api", componentRouter);
app.use("/api", departmentRouter);
app.use("/api", courseRouter);
app.use("/api", sectionRouter);
app.use("/api", labRouter);
app.use("/api", routineSlotRouter);
app.use("/api", experimentRouter);
app.use("/api", sessionRouter);
app.use("/api", analyticsRouter);
app.use("/api", stockRouter);
app.use("/api", quotaRouter);
app.use("/api", userRouter);
app.use("/api", availabilityRouter);
app.use("/api", requisitionRouter);
app.use("/api", borrowRouter);
app.use("/api", purchaseRouter);
app.use("/api", notificationRouter);
app.use("/api", damageRouter);
app.use("/api", suggestionRouter);
app.use("/api", penaltyRouter);
app.use("/api", auditRouter);

app.listen(env.PORT, () => {
  console.log(`LabLink API listening on port ${env.PORT}`);
  startBackgroundJobs();
});
